# Generated by Django 3.2.7 on 2021-09-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.icon', to_field='name'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryitem',
            unique_together={('content_type', 'object_id', 'category')},
        ),
        migrations.AlterIndexTogether(
            name='categoryitem',
            index_together={('content_type', 'object_id')},
        ),
    ]
