# Generated by Django 3.2.7 on 2021-09-19 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import markdownx.models
import components


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('label', models.CharField(db_index=True, max_length=64, verbose_name='Label')),
                ('content', markdownx.models.MarkdownxField(verbose_name='Content')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=models.SET(
                    components.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Email')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('text', models.TextField(verbose_name='Message')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=models.SET(
                    components.models.get_sentinel_user), related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_related',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_related', django.db.models.manager.Manager()),
            ],
        ),
    ]
